[workspace]
members = [
	"apps/messenger",
	# "apps/web/wasm",
	"config",
	"constants",
	"core/cli",
	"core/database",
	"core/env",
	"core/helpers",
	"core/logger",
	"core/network",
	"core/setup",
	"core/terminal",
	"macro",
	"proto/irc/message",
	"tests",
	"tools/license",
	"tools/readme",
]

[workspace.package]
version = "1.0.0"
authors = ["Mike 'PhiSyX' S."]
edition = "2021"
license-file = "./LICENSE"
publish = false

[workspace.dependencies]
phisyrc = { path = "./macro", package = "phisyrc-macro" }
cli = { path = "./core/cli", package = "phisyrc-cli" }
config = { path = "./config", package = "phisyrc-config" }
constants = { path = "./constants", package = "phisyrc-constants" }
database = { path = "./core/database", package = "phisyrc-database" }
env = { path = "./core/env", package = "phisyrc-env" }
helpers = { path = "./core/helpers", package = "phisyrc-helpers" }
lang = { git = "https://github.com/PhiSyX/lang" }
logger = { path = "./core/logger", package = "phisyrc-logger" }
network = { path = "./core/network", package = "phisyrc-network" }
setup = { path = "./core/setup", package = "phisyrc-setup" }
terminal = { path = "./core/terminal", package = "phisyrc-terminal" }

chrono = "^0.4"
clap = { version = "^4.0", features = ["derive", "env", "wrap_help"] }
futures = "^0.3"
serde = { version = "^1.0", features = ["derive"] }
tokio = { version = "^1.21", features = [
	"macros",
	"net",
	"rt-multi-thread",
	"sync",
	"time",
] }

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
