[package]
name = "phisyrc"
version = "0.1.0"
edition = "2021"
license-file = "./LICENSE"
publish = false

[[bin]]
name = "phisyrc"
path = "./phisyrc.rs"

[workspace]
members = ["cli", "env", "irc", "logger", "macro"]

[dependencies]
cli = { path = "cli", package = "phisyrcli" }
daemon = { path = "daemon", package = "phisyrcd" }
env = { path = "env", package = "phisyrc-env" }
irc = { path = "irc", package = "phisyrc-irc" }
phisyrc = { path = "macro", package = "phisyrc-macro" }

async-trait = "^0.1"
crossterm = { version = "^0.24", default-features = false, features = [
	"event-stream",
] }
futures = { version = "^0.3" }
tokio = { version = "^1.20", features = ["full"] }
tui = { version = "^0.18", default-features = false, features = ["crossterm"] }
