[workspace]
members = [
	"app",
	"app/ui/graphical",
	"app/ui/textual",
	"app/ui/web",
	"cli",
	"database",
	"env",
	"fs",
	"http",
	"irc",
	"logger",
	"macro",
	"shared",
	"tests",
	"tools/readme",
	"websocket",
]
