[workspace]
members = [
	"apps/messenger",
	"core/cli",
	"core/env",
	"core/terminal",
	"macro",
	"tools/readme",
]

[workspace.package]
version = "1.0.0"
authors = ["Mike 'PhiSyX' S."]
edition = "2021"
license-file = "./LICENSE"
publish = false

[workspace.dependencies]
phisyrc = { path = "./macro", package = "phisyrc-macro" }
cli = { path = "./core/cli", package = "phisyrc-cli" }
env = { path = "./core/env", package = "phisyrc-env" }
terminal = { path = "./core/terminal", package = "phisyrc-terminal" }

clap = { version = "^4.0", features = ["derive", "env", "wrap_help"] }
lazy_static = "^1.4"
tokio = { version = "^1.21", features = ["macros", "rt-multi-thread"] }
