[workspace]
members = ["apps", "core/cli", "macro", "tools/readme"]

[workspace.package]
version = "1.0.0"
authors = ["Mike 'PhiSyX' S."]
edition = "2021"
license-file = "./LICENSE"
publish = false

[workspace.dependencies]
phisyrc = { path = "./macro", package = "phisyrc-macro" }
cli = { path = "./core/cli", package = "phisyrc-cli" }

clap = { version = "^4.0", features = ["derive", "env", "wrap_help"] }
tokio = { version = "^1.21", features = ["macros", "rt-multi-thread"] }
