[workspace]
members = [
	"apps/messenger",
	"config",
	"constants",
	"core/cli",
	"core/env",
	"core/helpers",
	"core/logger",
	"core/terminal",
	"macro",
	"tools/readme",
]

[workspace.package]
version = "1.0.0"
authors = ["Mike 'PhiSyX' S."]
edition = "2021"
license-file = "./LICENSE"
publish = false

[workspace.dependencies]
phisyrc = { path = "./macro", package = "phisyrc-macro" }
cli = { path = "./core/cli", package = "phisyrc-cli" }
config = { path = "./config", package = "phisyrc-config" }
constants = { path = "./constants", package = "phisyrc-constants" }
env = { path = "./core/env", package = "phisyrc-env" }
helpers = { path = "./core/helpers", package = "phisyrc-helpers" }
logger = { path = "./core/logger", package = "phisyrc-logger" }
terminal = { path = "./core/terminal", package = "phisyrc-terminal" }

chrono = "^0.4"
clap = { version = "^4.0", features = ["derive", "env", "wrap_help"] }
futures = "^0.3"
serde = { version = "^1.0", features = ["derive"] }
tokio = { version = "^1.21", features = [
	"macros",
	"net",
	"rt-multi-thread",
	"sync",
	"time",
] }
