[info]
admin = ["Mike 'PhiSyX' S.", "PhiSyX", "admin@phisy.rc"]
description = "Serveur phisyRC"
name = "irc.phisy.rc"
network_name = "phisyRC"

[[listen]]
name = "irc.phisy.rc"
ip = "127.0.0.1"
port = 6667
#
# `password.secret` :  mot de passe secret.
# `password.algo`   :  algorithme de hachage à utiliser -- "plain" | "argon2"`
#               	   par défaut à "argon2" pour l'instant.
#
# Le mot de passe ci-dessous a été généré par la commande:
#
#   $ phisyrc make:password test
#
# Ce qui veut dire que le mot de passe en clair vaut "test".
#
password.algo = "argon2"
password.secret = "$argon2id$v=19$m=4096,t=3,p=1$bWQ5b2prMXBJY0UyNGRSc29wODZIZGk5ODduZkRLaTU$QwsRN6Ds44/mZb5abqBq8/Lzgb1Y33qRUcpUKXO6GF0"

[[listen]]
name = "localhost"
ip = "127.0.0.1"
port = 6668

