[package]
name = "phisyrc-helpers"
version.workspace = true
authors.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
path = "./lib.rs"

[dependencies]
deunicode = "^1.3"
regex = "^1.6"
rust-crypto = { version = "^0.2" }
