# Renommer ce fichier en "config.toml", et modifier les occurrences de "<user>"
# par le nom de ton utilisateur courant.
#
# Cela permet de ne pas avoir le chemin complet dont le nom d'utilisateur
# y est inclus dans le fichier build en release.
# cargo build --release (output "./target/release/phisyrc")
# strings ./target/release/phisyrc | grep <user>

[alias]
b = "build --release -Z unstable-options --out-dir .phisyrc/"

[build]
rustflags = [
	"--remap-path-prefix=C:\\Users\\<user>\\=",  # Windows
	"--remap-path-prefix=/mnt/c/Users/<user>/=", # Windows + WSL
	"--remap-path-prefix=/home/<user>/=",        # Linux, ...
]
