[package]
name = "phisyrc-logger"
version = "0.1.0"
edition = "2021"
license-file = "../LICENSE"
publish = false

[lib]
path = "./lib.rs"

[dependencies]
chrono = { path = "../patches/chrono" }
log = { version = "^0.4", features = ["std"] }
cli = { path = "../cli", package = "phisyrcli" }
