[package]
name = "phisyrc-terminal"
version.workspace = true
authors.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
path = "./lib.rs"

[dependencies]
lazy_static.workspace = true
regex = "^1.6"
unicode-width = "^0.1"
