[package]
name = "proto-irc-replies"
version.workspace = true
authors.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
path = "./lib.rs"

[features]
default = []
json = ["serde_json"]

[dependencies]
lang.workspace = true
logger.workspace = true
serde.workspace = true
serde_json = { version = "^1.0", optional = true }
irc_msg = { workspace = true, features = ["json"] }
