name: Rust CI

on:
    push:
        branches:
            - main
            - "feat/**"
    pull_request:
        branches:
            - main
            - "feat/**"

env:
    CARGO_TERM_COLOR: always

jobs:
    check_license_source:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: configure la toolchain et le cache de Rust
              uses: actions-rust-lang/setup-rust-toolchain@v1.3.4

            - name: vérifier les en-têtes de licences des fichiers du projet
              uses: actions-rs/cargo@v1.0.1
              with:
                  command: run
                  args: --release --bin check-license

    fmt_lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: configure la toolchain et le cache de Rust
              uses: actions-rust-lang/setup-rust-toolchain@v1.3.4

            - name: formatage
              uses: actions-rs/cargo@v1.0.1
              with:
                  command: fmt
                  args: --all -- --check

            - name: linter
              uses: actions-rs/cargo@v1.0.1
              with:
                  command: clippy
                  # dead_code : il est possible qu'il y ait du code non utilisé,
                  # ça n'a pas d'importance. Le build enlève tout code mort de
                  # toute façon.
                  args: --workspace --all-targets -- -D warnings -A dead_code

    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: configure la toolchain et le cache de Rust
              uses: actions-rust-lang/setup-rust-toolchain@v1.3.4

            - name: tests unitaires
              uses: actions-rs/cargo@v1.0.1
              with:
                  command: test
                  args: --all --verbose
