name: Rust CI

on:
  push:
    branches:
        - main
        - 'feat/**'
  pull_request:
    branches:
        - main
        - 'feat/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: mise à jour de la toolchain
      run: |
        rustup update
        rustup install nightly
        rustup default nightly
        rustup component add clippy rustfmt

    - name: information de la toolchain
      run: |
        cargo --version --verbose
        rustc --version
        cargo clippy --version

    - name: formatage & linter
      run: |
        cargo fmt -- --check
        # dead_code : il est possible qu'il y ait du code non utilisé, ça n'a
        #    pas d'importance.
        #    Le build enlève tout code mort de toute façon.
        #
        # clippy::uninlined-format-args : c'est quoi cette règle à la noix?
        #    Je n'ai pas forcément envie de la respecter, pour l'instant.
        cargo clippy -- -D warnings -A dead_code -A clippy::uninlined-format-args

    - name: tests unitaires
      run: cargo test --all --verbose
