name: Web CI

on:
    push:
        branches:
            - main
            - "feat/**"
    pull_request:
        branches:
            - main
            - "feat/**"

jobs:
    check_fmt:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v3
            - name: Installe pnpm
              uses: pnpm/action-setup@v2.2.4
              with:
                  version: 7
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
            - name: Installation des dépendances
              run: pnpm install
            - name: Vérifier le formatage
              run: pnpm run check:fmt

    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v3
            - name: Installe pnpm
              uses: pnpm/action-setup@v2.2.4
              with:
                  version: 7
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
            - name: Installation des dépendances
              run: pnpm install
            - name: Executer les tests
              run: pnpm web test:unit
